[package]
name = "lt_client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"
path = "src/bin/client_test.rs"

[profile.dev]
opt-level = 2
#overflow-checks = false  

[dependencies]
lt_server = { path = "../lt_server" }
rosc = "0.10.1"
socket2 = "0.5.8"

